services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - SECRET=moacirehfoda
      - PORT=3000
      - CONNECTION_URL=mongodb+srv://josesicupiraneto:Zvj38Q3XVleGYPin@cluster0.earia.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
